//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIEmployee.SessionSrv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Session", Namespace="http://schemas.datacontract.org/2004/07/CinemaServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Session : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnterTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExitTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GUIEmployee.SessionSrv.Movie MovieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GUIEmployee.SessionSrv.Room RoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GUIEmployee.SessionSrv.Seat[][] SeatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SessionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterTime {
            get {
                return this.EnterTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterTimeField, value) != true)) {
                    this.EnterTimeField = value;
                    this.RaisePropertyChanged("EnterTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExitTime {
            get {
                return this.ExitTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExitTimeField, value) != true)) {
                    this.ExitTimeField = value;
                    this.RaisePropertyChanged("ExitTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GUIEmployee.SessionSrv.Movie Movie {
            get {
                return this.MovieField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieField, value) != true)) {
                    this.MovieField = value;
                    this.RaisePropertyChanged("Movie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GUIEmployee.SessionSrv.Room Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GUIEmployee.SessionSrv.Seat[][] Seats {
            get {
                return this.SeatsField;
            }
            set {
                if ((object.ReferenceEquals(this.SeatsField, value) != true)) {
                    this.SeatsField = value;
                    this.RaisePropertyChanged("Seats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://schemas.datacontract.org/2004/07/CinemaServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MovieIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgeLimit {
            get {
                return this.AgeLimitField;
            }
            set {
                if ((this.AgeLimitField.Equals(value) != true)) {
                    this.AgeLimitField = value;
                    this.RaisePropertyChanged("AgeLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MovieId {
            get {
                return this.MovieIdField;
            }
            set {
                if ((this.MovieIdField.Equals(value) != true)) {
                    this.MovieIdField = value;
                    this.RaisePropertyChanged("MovieId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Room", Namespace="http://schemas.datacontract.org/2004/07/CinemaServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Room : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfSeatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoomNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfSeats {
            get {
                return this.NumberOfSeatsField;
            }
            set {
                if ((this.NumberOfSeatsField.Equals(value) != true)) {
                    this.NumberOfSeatsField = value;
                    this.RaisePropertyChanged("NumberOfSeats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoomNumber {
            get {
                return this.RoomNumberField;
            }
            set {
                if ((this.RoomNumberField.Equals(value) != true)) {
                    this.RoomNumberField = value;
                    this.RaisePropertyChanged("RoomNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Seat", Namespace="http://schemas.datacontract.org/2004/07/CinemaServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class Seat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GUIEmployee.SessionSrv.Room RoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeatNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GUIEmployee.SessionSrv.Room Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowNumber {
            get {
                return this.RowNumberField;
            }
            set {
                if ((this.RowNumberField.Equals(value) != true)) {
                    this.RowNumberField = value;
                    this.RaisePropertyChanged("RowNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeatId {
            get {
                return this.SeatIdField;
            }
            set {
                if ((this.SeatIdField.Equals(value) != true)) {
                    this.SeatIdField = value;
                    this.RaisePropertyChanged("SeatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeatNumber {
            get {
                return this.SeatNumberField;
            }
            set {
                if ((this.SeatNumberField.Equals(value) != true)) {
                    this.SeatNumberField = value;
                    this.RaisePropertyChanged("SeatNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SessionSrv.ISessionService")]
    public interface ISessionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/insertSession", ReplyAction="http://tempuri.org/ISessionService/insertSessionResponse")]
        int insertSession(int movieId, string EnterTime, string ExitTime, string Date, double Price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/insertSession", ReplyAction="http://tempuri.org/ISessionService/insertSessionResponse")]
        System.Threading.Tasks.Task<int> insertSessionAsync(int movieId, string EnterTime, string ExitTime, string Date, double Price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/updateSession", ReplyAction="http://tempuri.org/ISessionService/updateSessionResponse")]
        int updateSession(int MovieId, string Date, string EnterTime, string ExitTime, double Price, int SessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/updateSession", ReplyAction="http://tempuri.org/ISessionService/updateSessionResponse")]
        System.Threading.Tasks.Task<int> updateSessionAsync(int MovieId, string Date, string EnterTime, string ExitTime, double Price, int SessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/insertSeatSchedule", ReplyAction="http://tempuri.org/ISessionService/insertSeatScheduleResponse")]
        int[] insertSeatSchedule(int sessionId, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/insertSeatSchedule", ReplyAction="http://tempuri.org/ISessionService/insertSeatScheduleResponse")]
        System.Threading.Tasks.Task<int[]> insertSeatScheduleAsync(int sessionId, int roomNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/updateSeatSchedule", ReplyAction="http://tempuri.org/ISessionService/updateSeatScheduleResponse")]
        int updateSeatSchedule(int sessionId, int seatId, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/updateSeatSchedule", ReplyAction="http://tempuri.org/ISessionService/updateSeatScheduleResponse")]
        System.Threading.Tasks.Task<int> updateSeatScheduleAsync(int sessionId, int seatId, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/deleteSession", ReplyAction="http://tempuri.org/ISessionService/deleteSessionResponse")]
        int deleteSession(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/deleteSession", ReplyAction="http://tempuri.org/ISessionService/deleteSessionResponse")]
        System.Threading.Tasks.Task<int> deleteSessionAsync(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/deleteSeatsFromSession", ReplyAction="http://tempuri.org/ISessionService/deleteSeatsFromSessionResponse")]
        int deleteSeatsFromSession(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/deleteSeatsFromSession", ReplyAction="http://tempuri.org/ISessionService/deleteSeatsFromSessionResponse")]
        System.Threading.Tasks.Task<int> deleteSeatsFromSessionAsync(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/getSession", ReplyAction="http://tempuri.org/ISessionService/getSessionResponse")]
        GUIEmployee.SessionSrv.Session getSession(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/getSession", ReplyAction="http://tempuri.org/ISessionService/getSessionResponse")]
        System.Threading.Tasks.Task<GUIEmployee.SessionSrv.Session> getSessionAsync(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/getSessions", ReplyAction="http://tempuri.org/ISessionService/getSessionsResponse")]
        GUIEmployee.SessionSrv.Session[] getSessions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/getSessions", ReplyAction="http://tempuri.org/ISessionService/getSessionsResponse")]
        System.Threading.Tasks.Task<GUIEmployee.SessionSrv.Session[]> getSessionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/getMovieSessions", ReplyAction="http://tempuri.org/ISessionService/getMovieSessionsResponse")]
        GUIEmployee.SessionSrv.Session[] getMovieSessions(int movieId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/getMovieSessions", ReplyAction="http://tempuri.org/ISessionService/getMovieSessionsResponse")]
        System.Threading.Tasks.Task<GUIEmployee.SessionSrv.Session[]> getMovieSessionsAsync(int movieId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/getSessionSeats", ReplyAction="http://tempuri.org/ISessionService/getSessionSeatsResponse")]
        GUIEmployee.SessionSrv.Seat[] getSessionSeats(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/getSessionSeats", ReplyAction="http://tempuri.org/ISessionService/getSessionSeatsResponse")]
        System.Threading.Tasks.Task<GUIEmployee.SessionSrv.Seat[]> getSessionSeatsAsync(int sessionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISessionServiceChannel : GUIEmployee.SessionSrv.ISessionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionServiceClient : System.ServiceModel.ClientBase<GUIEmployee.SessionSrv.ISessionService>, GUIEmployee.SessionSrv.ISessionService {
        
        public SessionServiceClient() {
        }
        
        public SessionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int insertSession(int movieId, string EnterTime, string ExitTime, string Date, double Price) {
            return base.Channel.insertSession(movieId, EnterTime, ExitTime, Date, Price);
        }
        
        public System.Threading.Tasks.Task<int> insertSessionAsync(int movieId, string EnterTime, string ExitTime, string Date, double Price) {
            return base.Channel.insertSessionAsync(movieId, EnterTime, ExitTime, Date, Price);
        }
        
        public int updateSession(int MovieId, string Date, string EnterTime, string ExitTime, double Price, int SessionId) {
            return base.Channel.updateSession(MovieId, Date, EnterTime, ExitTime, Price, SessionId);
        }
        
        public System.Threading.Tasks.Task<int> updateSessionAsync(int MovieId, string Date, string EnterTime, string ExitTime, double Price, int SessionId) {
            return base.Channel.updateSessionAsync(MovieId, Date, EnterTime, ExitTime, Price, SessionId);
        }
        
        public int[] insertSeatSchedule(int sessionId, int roomNumber) {
            return base.Channel.insertSeatSchedule(sessionId, roomNumber);
        }
        
        public System.Threading.Tasks.Task<int[]> insertSeatScheduleAsync(int sessionId, int roomNumber) {
            return base.Channel.insertSeatScheduleAsync(sessionId, roomNumber);
        }
        
        public int updateSeatSchedule(int sessionId, int seatId, string status) {
            return base.Channel.updateSeatSchedule(sessionId, seatId, status);
        }
        
        public System.Threading.Tasks.Task<int> updateSeatScheduleAsync(int sessionId, int seatId, string status) {
            return base.Channel.updateSeatScheduleAsync(sessionId, seatId, status);
        }
        
        public int deleteSession(int sessionId) {
            return base.Channel.deleteSession(sessionId);
        }
        
        public System.Threading.Tasks.Task<int> deleteSessionAsync(int sessionId) {
            return base.Channel.deleteSessionAsync(sessionId);
        }
        
        public int deleteSeatsFromSession(int sessionId) {
            return base.Channel.deleteSeatsFromSession(sessionId);
        }
        
        public System.Threading.Tasks.Task<int> deleteSeatsFromSessionAsync(int sessionId) {
            return base.Channel.deleteSeatsFromSessionAsync(sessionId);
        }
        
        public GUIEmployee.SessionSrv.Session getSession(int sessionId) {
            return base.Channel.getSession(sessionId);
        }
        
        public System.Threading.Tasks.Task<GUIEmployee.SessionSrv.Session> getSessionAsync(int sessionId) {
            return base.Channel.getSessionAsync(sessionId);
        }
        
        public GUIEmployee.SessionSrv.Session[] getSessions() {
            return base.Channel.getSessions();
        }
        
        public System.Threading.Tasks.Task<GUIEmployee.SessionSrv.Session[]> getSessionsAsync() {
            return base.Channel.getSessionsAsync();
        }
        
        public GUIEmployee.SessionSrv.Session[] getMovieSessions(int movieId) {
            return base.Channel.getMovieSessions(movieId);
        }
        
        public System.Threading.Tasks.Task<GUIEmployee.SessionSrv.Session[]> getMovieSessionsAsync(int movieId) {
            return base.Channel.getMovieSessionsAsync(movieId);
        }
        
        public GUIEmployee.SessionSrv.Seat[] getSessionSeats(int sessionId) {
            return base.Channel.getSessionSeats(sessionId);
        }
        
        public System.Threading.Tasks.Task<GUIEmployee.SessionSrv.Seat[]> getSessionSeatsAsync(int sessionId) {
            return base.Channel.getSessionSeatsAsync(sessionId);
        }
    }
}
