//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleTesting.CustomerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerServiceReference.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/insertCustomer", ReplyAction="http://tempuri.org/ICustomerService/insertCustomerResponse")]
        int insertCustomer(string fName, string lName, string city, string address, string email, string phoneNo, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/insertCustomer", ReplyAction="http://tempuri.org/ICustomerService/insertCustomerResponse")]
        System.Threading.Tasks.Task<int> insertCustomerAsync(string fName, string lName, string city, string address, string email, string phoneNo, string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : ConsoleTesting.CustomerServiceReference.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<ConsoleTesting.CustomerServiceReference.ICustomerService>, ConsoleTesting.CustomerServiceReference.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int insertCustomer(string fName, string lName, string city, string address, string email, string phoneNo, string username, string password) {
            return base.Channel.insertCustomer(fName, lName, city, address, email, phoneNo, username, password);
        }
        
        public System.Threading.Tasks.Task<int> insertCustomerAsync(string fName, string lName, string city, string address, string email, string phoneNo, string username, string password) {
            return base.Channel.insertCustomerAsync(fName, lName, city, address, email, phoneNo, username, password);
        }
    }
}
